### ISSUE TITLE
Transfer Bandwidth

### ISSUE THREAD

**Issue by YimingLi-1996** [HMS-Core/hms-nearby-demo#3]
Hi! I found out that the Nearby Connection has really impressive bandwidth. In the best case I could transfer a 227 MB mp4 file within 8 seconds. Is there a official bandwidth limit? What is the maximum file size supported? Thank you!

**Comment by yczhaocau** [comment]
In the lab environment, the maximum transmission rate is 80 MB/s. In general environment, the maximum transmission rate is 60 MB/s. The transmission rate depends on the environment and mobile phone model. The maximum size of a file is 512 GB.
