### ISSUE TITLE
Group Chat

### ISSUE THREAD

**Issue by YimingLi-1996** [HMS-Core/hms-nearby-demo#4]
Hi! What is the optimum method to realize group chat feature with Nearby Connection? Thanks!

**Comment by yczhaocau** [comment]
Broadcasting and scanning using POLICY_STAR.A point-to-point connection policy that supports a 1-to-N or star-shaped connection topology. This enables the connection of devices within a radio range in a star shape, where each device can, at any given time, play the role of either a hub (where it can accept incoming connections from other devices), or a branch (where it can initiate an outgoing connection to a single hub). However, the device cannot play both roles at the same time.
